<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Start Page</title>

    <link href="css/startPage.css" rel="stylesheet" type="text/css"/>

</head>
<body>

<a href="/resume">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    ABOUT ME
</a>
<a href="/aboutProject">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    ABOUT PROJECT
</a>

<a href="/helloSweaterPage">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    MY WORK
</a>

</body>
</html>